apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-app
        image: 503698126220.dkr.ecr.us-east-1.amazonaws.com/notionx-frontend:manual-v1 # Placeholder
        ports:
        - containerPort: 3001
        env:
        - name: AI_API_URL
          # Kubernetes DNS: service-name.namespace.svc.cluster.local
          value: "http://ai-api-service.default.svc.cluster.local:8080/api/generate"