apiVersion: apps/v1
kind: Deployment
metadata:
  name: notionx-frontend-deployment
  labels:
    app: notionx-frontend
spec:
  replicas: 2 # Run two instances for basic high-availability
  selector:
    matchLabels:
      app: notionx-frontend
  template:
    metadata:
      labels:
        app: notionx-frontend
    spec:
      containers:
      - name: notionx-frontend
        image: __IMAGE_URL__:__IMAGE_TAG__ # Jenkins will replace these placeholders
        ports:
        - containerPort: 3000
        envFrom: # Pulls all key-value pairs from the specified secret
        - secretRef:
            name: firebase-config # This secret will contain your Firebase credentials