apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  annotations:
    # This tells the AWS load balancer which path to check for health
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on
      targetPort: 3001
  type: LoadBalancer # We will use an Ingress later, this is for testing