apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on
      targetPort: 3001
  type: LoadBalancer # We will use an Ingress later, this is for testing