# /notionx-frontend/.github/workflows/deploy.yml
name: Deploy Frontend to EKS

on:
  push:
    branches: ["master"]

env:
  ECR_REPOSITORY: notionx-frontend
  
jobs:
  build-and-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Validate Secrets
      run: |
        echo "LIVEBLOCKS_PRIVATE_KEY length: ${{ env.LIVEBLOCKS_SECRET_LENGTH }}"
        echo "EDGE_STORE_ACCESS_KEY length: ${{ env.EDGE_ACCESS_KEY_LENGTH }}"
        echo "EDGE_STORE_SECRET_KEY length: ${{ env.EDGE_SECRET_KEY_LENGTH }}"
        echo "AWS_ACCESS_KEY_ID length: ${{ env.AWS_KEY_ID_LENGTH }}"
        echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY length: ${{ env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}"
        echo "FIREBASE_SERVICE_KEY length: ${{ env.FIREBASE_SERVICE_KEY }}"
      env:
        # We create temporary env vars to hold the length of each secret
        LIVEBLOCKS_SECRET_LENGTH: ${{ join(secrets.LIVEBLOCKS_PRIVATE_KEY, 'x') && 1 }}
        EDGE_ACCESS_KEY_LENGTH: ${{ join(secrets.EDGE_STORE_ACCESS_KEY, 'x') && 1 }}
        EDGE_SECRET_KEY_LENGTH: ${{ join(secrets.EDGE_STORE_SECRET_KEY, 'x') && 1 }}
        AWS_KEY_ID_LENGTH: ${{ join(secrets.AWS_ACCESS_KEY_ID, 'x') && 1 }}

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Create .env.local file for build
      run: |
        cat <<EOF > .env.local
        # This file is dynamically created in CI/CD for the build process
        LIVEBLOCKS_PRIVATE_KEY=${{ secrets.LIVEBLOCKS_PRIVATE_KEY }}
        EDGE_STORE_ACCESS_KEY=${{ secrets.EDGE_STORE_ACCESS_KEY }}
        EDGE_STORE_SECRET_KEY=${{ secrets.EDGE_STORE_SECRET_KEY }}
        EOF

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push Docker Image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Deploy to Amazon EKS
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
        sed -i 's|image: .*|image: ${{ steps.build-image.outputs.image }}|' ks/deployment.yaml
        kubectl apply -f k8s/